### ISSUE TITLE
Conversion Error from/to ED1950

### ISSUE THREAD

**Issue by Giovefi** [ClemRz/TWCC#68]
We are studying coordinate conversion and we use also your really good job to check our software results.

We found a possible error in conversion from/to ED 1950 GEO

In fact we also use UltraSoft site to have another check and our results are compliant with that site.

Detailed situation:
- from WGS84 GEO to WGS84 UTM is OK
- from WGS84 GEO to ED1950 UTM is OK
- from WGS84 GEO to ED1950 GEO we have 4 seconds of difference in Long
- from ED1950 UTM to ED1950 GEO we found the same 4 seconds Long error 

We hope You could check this situation and also please give us a feedback.

Thanks in advance and best regards.

**Comment by ClemRz** [comment]
Hi, thank you for reporting this.

Unfortunately this is a known limitation of JS computation power. 
JavaScript rounds numbers during calculus, more importantly when it's about trigonometric like in the case of ED50 Geo.
The library used to run the conversions is https://github.com/proj4js/proj4js
Please feel free to test directly agains the JS library and report any discrepancy at https://github.com/proj4js/proj4js/issues/

Thank you.
