### ISSUE TITLE
outil de conversion en italie

### ISSUE THREAD

**Issue by urien** [ClemRz/TWCC#7]
Pour des cavités de Toscane
Les coordonnées sont en Goos Boaga, il y a sur le site en question un outils de conversion

http://www.speleotoscana.it/programmi_php/catasto/coord.php?x=106&y=20

Sur les fiches détaillées il y a également les coordonnées UTM

http://www.speleotoscana.it/programmi_php/catasto/grotta.php?num=945

Mais quand on utilise l'outil de conversion de TWCC on n'obtient pas le même résultat que sur le site indiqué. Il doit y avoir une erreur, qui vient peut être du choix des zones UTM

Est-ce que Goos Boaga Est ne correspond pas au fuseau UTM 33 et Goos Boaga Ouest au fuseau 32 et que le convertisseur de TWCC ne prendrait pas le bon fuseau.

**Comment by ClemRz** [comment]
Bonjour Fred,

Est ce que tu pourrais vérifier que la nouvelle version de TWCC (http://twcc.fr) donne la bonne conversion stp?

**Comment by urien** [comment]
Merci d'avoir regardé le problème

Je vais faire des tests dimanche

A bientôt

2015-01-08 16:28 GMT+01:00 Clément Ronzon <notifications@github.com>:

**Comment by urien** [comment]
Bonjour,

Cela ne fonctionne pas

Voila ce que donne le site de conversion en ligne Italien

​
Et voila ce que donne TWCC (http://twcc.fr/#)


​

Il y a un truc un peu étrange : pour GWS84 on ne peut pas changer le fuseau
et à priori c'est dans le fuseau 32 ou 33

**Comment by ClemRz** [comment]
Salut,
Je pense que tu as choisi "Gauss Boaga Fuso Est" au lieux de "Gauss Boaga Fuso Ovest":
http://twcc.fr/fr/?sc=SR-ORG%253A4685&dc=SR-ORG%253A14-UTM&wgs84=11.160027272199217%252C43.915879189830726&z=15&mt=terrain

**Comment by urien** [comment]
Salut,

Merci !

Cela semble bon, il y a une différence entre TWCC et le site Italien mais
la différence n'est pas significative

  TWCC logiciel italien
 636365,58 636340 0,004020%  4881959,2 4882123 -0,003355%

2015-01-11 16:59 GMT+01:00 Clément Ronzon <notifications@github.com>:

**Comment by ClemRz** [comment]
Cool!
Je ferme le bug alors.
A+
